FROM node:20-alpine

WORKDIR /app

# 复制项目文件
COPY frontend/package*.json frontend/pnpm-lock.yaml ./

# 安装依赖
RUN npm install -g pnpm
RUN pnpm install

# 复制其余源代码
COPY frontend/ ./

# 构建应用
RUN pnpm build

# 暴露端口
EXPOSE 8008

# 启动服务
CMD ["pnpm", "start"] 