FROM node:20-alpine

WORKDIR /app

# 复制项目文件
COPY backend/package*.json backend/pnpm-lock.yaml ./

# 安装依赖
RUN npm install -g pnpm
RUN pnpm install

# 复制其余源代码
COPY backend/ ./

# 暴露端口
EXPOSE 3001

# 启动服务
CMD ["pnpm", "start"] 